### PR TITLE
Workflow proposal for MacOS extension

### PR DESCRIPTION
**Pull request by AleCandido**

### CODE REVIEW

**Comment by AleCandido** [comment]
https://github.com/pypa/cibuildwheel/discussions/1601

**Comment by AleCandido** [comment]
https://github.com/matthew-brett/delocate?tab=readme-ov-file#making-dual-architecture-binaries

**Comment by AleCandido** [comment]
Currently, we're able to build MacOS wheels, but unfortunately not `universal2` ones d0e8d91 (in particular, the wheel currently built are only for MacOS Intel).

In order to find a solution, we should investigate more the content of the previous link.

I'm not sure whether we need or not a MacOS machine with a Silicon processor to build the corresponding wheel.
Unfortunately, that would be only available to GitHub Team or Enterprise Cloud (so for sure not to the @niclaurenti account).
https://docs.github.com/en/actions/using-github-hosted-runners/about-larger-runners/about-larger-runners#about-macos-larger-runners
https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources

However, `maturin-action` is able to build universal wheels on MacOS, and it doesn't require a Silicon machine (and I'm pretty sure it doesn't use a virtual machine as well). So, it should be possible, *more or less* (not sure how painful).

**Comment by AleCandido** [comment]
```sh
[...]
  ld: symbol(s) not found for architecture x86_64
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
  make[2]: *** [libgsl.la] Error 1
  make[1]: *** [all-recursive] Error 1
  make: *** [all] Error 2
                                                             ✕ 64.47s
Error: Command brew reinstall gcc && wget https://mirror.ibcp.fr/pub/gnu/gsl/gsl-2.7.1.tar.gz && tar -zxvf gsl-2.7.1.tar.gz && cd gsl-2.7.1 && ./configure && make && make install && cd ..
```

**Comment by niclaurenti** [comment]
> ```shell
> [...]
>   ld: symbol(s) not found for architecture x86_64
>   clang: error: linker command failed with exit code 1 (use -v to see invocation)
>   make[2]: *** [libgsl.la] Error 1
>   make[1]: *** [all-recursive] Error 1
>   make: *** [all] Error 2
>                                                              ✕ 64.47s
> Error: Command brew reinstall gcc && wget https://mirror.ibcp.fr/pub/gnu/gsl/gsl-2.7.1.tar.gz && tar -zxvf gsl-2.7.1.tar.gz && cd gsl-2.7.1 && ./configure && make && make install && cd ..
> ```

Yes here I wanted to compile intel and arm64 architectures instead of universal one, since previously the error was `Command delocate-wheel --require-archs x86_64,arm64` so maybe it doesn't like `universal2`.
But the error was that in this way he tries to compile an arm64 on an intel machine: https://cibuildwheel.readthedocs.io/en/stable/options/#examples_2
Now I added auto in front to see if it works

**Comment by AleCandido** [comment]
I believe that `auto` will resolve to `x86_64` once more, because that's the arch of the machine you're running on.

However, the issue might be strictly related to the usage of `brew` and some libraries. So, you might try to circumvent it by changing those commands (if it works for `arm64` it will also work for `universal2`, that is essentially the sum of `x86_64` + `arm64` in a single package).

**Review by niclaurenti — APPROVED** [review]

**Pull request merged**
